### ISSUE TITLE
Discussion: Add own favicon upload?

### ISSUE THREAD

**Issue by Bellfalasch** [selbekk/app-favicon#2]
I've actually had this on my never ending todo-list for a while. So very pleased to see you did such an excellent job with this.

A few suggestions I had for the app I would make might benefit your app. Do as you please with my ideas, they're mostly just me trying to discuss and weigh pros and cons about them. What do you think?

favicon.ico is a special format, it's perhaps not an image that should be scaled even as that often screws it up. You can ofc use .png and most modern browsers will use that. But I've found loads and loads programs with legacy code still use the .ico file, and only that. Even loads of crawlers out there only assumes people have a favicon.ico file on root. What this does is it adds loads of 404 on my server for that .ico file on root. So my point here is that it might be valuable to still serve favicon.ico (from root with a url filter) and because of it's tiny scale - let user control it separately (if they want, ofc).

What do you think?

**Comment by selbekk** [comment]
Hi @Bellfalasch - glad to hear from you again, and sorry it took me this long to notice your comment.

Although favicon.ico is only needed by older versions of IE - and the usecases for it are shrinking as we speak - I understand what you're getting at. I can get around to fixing it this weekend, or I would love a PR for it :+1:

**Comment by Bellfalasch** [comment]
I never answered here, but agreed, the need for favicon.ico is dropping faster than a metal glove in water. Let's close the issue.
