### ISSUE TITLE
Discussion: Add manifest files for mobiles

### ISSUE THREAD

**Issue by Bellfalasch** [selbekk/app-favicon#3]
I don't know much about the details of this, but what I've gathered is that mobiles can now use an XML format file (or two, not sure) to specify more details about favicons and behavior.

Is this something that should be added to this app or is it completely out of scope? Seen some activity in the forums about struggles here. See here for more details:
https://discuss.enonic.com/t/how-to-set-up-favicons/361

**Comment by selbekk** [comment]
Hi again! As far as I've understood, the manifest.json file is deprecated as of now ([http://caniuse.com/#feat=offline-apps](link)).

**Comment by Bellfalasch** [comment]
Notification has a way of not getting to me. Only half a year later ... but yes, I agree. I'll close this issue until the entire spec has matured more.
